### ISSUE TITLE
Top left title should be clickable

### ISSUE THREAD

**Issue by stianfro** [jishono/jishono-baksida#3]
From a UX perspective, the top left title should be clickable and lead to the front/default page

![image](https://user-images.githubusercontent.com/26657174/89719568-fb89fe00-d9c9-11ea-9ea8-5237bc48a84e.png)

**Comment by stianfro** [comment]
https://github.com/jishono/jishono-baksida/commit/766664bf40ca60f8a1c9370e95210124ef53944a

**Comment by pergpau** [comment]
fixed on commit https://github.com/jishono/jishono-baksida/commit/766664bf40ca60f8a1c9370e95210124ef53944a
